import numpy as np
import torch
import clip
from tqdm.notebook import tqdm
from pkg_resources import packaging
from imagenetv2_pytorch import ImageNetV2Dataset
import os

print("Torch version:", torch.__version__)

# check convention embedding
embed_file = "../../clip_embed/sunrgbd_clip_a+cname_rn50_manyprompt_20c_ov3det.npy"
embed = np.load(embed_file)
breakpoint()

# # Loading the model
# Download and instantiate a CLIP model using the `clip` module that we just installed.
clip.available_models()
model, preprocess = clip.load("RN50")

input_resolution = model.visual.input_resolution
context_length = model.context_length
vocab_size = model.vocab_size

print("Model parameters:", f"{np.sum([int(np.prod(p.shape)) for p in model.parameters()]):,}")
print("Input resolution:", input_resolution)
print("Context length:", context_length)
print("Vocab size:", vocab_size)

# imagenet_classes = ["tench", "goldfish", "great white shark", "tiger shark", "hammerhead shark", "electric ray", "stingray", "rooster", "hen", "ostrich", "brambling", "goldfinch", "house finch", "junco", "indigo bunting", "American robin", "bulbul", "jay", "magpie", "chickadee", "American dipper", "kite (bird of prey)", "bald eagle", "vulture", "great grey owl", "fire salamander", "smooth newt", "newt", "spotted salamander", "axolotl", "American bullfrog", "tree frog", "tailed frog", "loggerhead sea turtle", "leatherback sea turtle", "mud turtle", "terrapin", "box turtle", "banded gecko", "green iguana", "Carolina anole", "desert grassland whiptail lizard", "agama", "frilled-necked lizard", "alligator lizard", "Gila monster", "European green lizard", "chameleon", "Komodo dragon", "Nile crocodile", "American alligator", "triceratops", "worm snake", "ring-necked snake", "eastern hog-nosed snake", "smooth green snake", "kingsnake", "garter snake", "water snake", "vine snake", "night snake", "boa constrictor", "African rock python", "Indian cobra", "green mamba", "sea snake", "Saharan horned viper", "eastern diamondback rattlesnake", "sidewinder rattlesnake", "trilobite", "harvestman", "scorpion", "yellow garden spider", "barn spider", "European garden spider", "southern black widow", "tarantula", "wolf spider", "tick", "centipede", "black grouse", "ptarmigan", "ruffed grouse", "prairie grouse", "peafowl", "quail", "partridge", "african grey parrot", "macaw", "sulphur-crested cockatoo", "lorikeet", "coucal", "bee eater", "hornbill", "hummingbird", "jacamar", "toucan", "duck", "red-breasted merganser", "goose", "black swan", "tusker", "echidna", "platypus", "wallaby", "koala", "wombat", "jellyfish", "sea anemone", "brain coral", "flatworm", "nematode", "conch", "snail", "slug", "sea slug", "chiton", "chambered nautilus", "Dungeness crab", "rock crab", "fiddler crab", "red king crab", "American lobster", "spiny lobster", "crayfish", "hermit crab", "isopod", "white stork", "black stork", "spoonbill", "flamingo", "little blue heron", "great egret", "bittern bird", "crane bird", "limpkin", "common gallinule", "American coot", "bustard", "ruddy turnstone", "dunlin", "common redshank", "dowitcher", "oystercatcher", "pelican", "king penguin", "albatross", "grey whale", "killer whale", "dugong", "sea lion", "Chihuahua", "Japanese Chin", "Maltese", "Pekingese", "Shih Tzu", "King Charles Spaniel", "Papillon", "toy terrier", "Rhodesian Ridgeback", "Afghan Hound", "Basset Hound", "Beagle", "Bloodhound", "Bluetick Coonhound", "Black and Tan Coonhound", "Treeing Walker Coonhound", "English foxhound", "Redbone Coonhound", "borzoi", "Irish Wolfhound", "Italian Greyhound", "Whippet", "Ibizan Hound", "Norwegian Elkhound", "Otterhound", "Saluki", "Scottish Deerhound", "Weimaraner", "Staffordshire Bull Terrier", "American Staffordshire Terrier", "Bedlington Terrier", "Border Terrier", "Kerry Blue Terrier", "Irish Terrier", "Norfolk Terrier", "Norwich Terrier", "Yorkshire Terrier", "Wire Fox Terrier", "Lakeland Terrier", "Sealyham Terrier", "Airedale Terrier", "Cairn Terrier", "Australian Terrier", "Dandie Dinmont Terrier", "Boston Terrier", "Miniature Schnauzer", "Giant Schnauzer", "Standard Schnauzer", "Scottish Terrier", "Tibetan Terrier", "Australian Silky Terrier", "Soft-coated Wheaten Terrier", "West Highland White Terrier", "Lhasa Apso", "Flat-Coated Retriever", "Curly-coated Retriever", "Golden Retriever", "Labrador Retriever", "Chesapeake Bay Retriever", "German Shorthaired Pointer", "Vizsla", "English Setter", "Irish Setter", "Gordon Setter", "Brittany dog", "Clumber Spaniel", "English Springer Spaniel", "Welsh Springer Spaniel", "Cocker Spaniel", "Sussex Spaniel", "Irish Water Spaniel", "Kuvasz", "Schipperke", "Groenendael dog", "Malinois", "Briard", "Australian Kelpie", "Komondor", "Old English Sheepdog", "Shetland Sheepdog", "collie", "Border Collie", "Bouvier des Flandres dog", "Rottweiler", "German Shepherd Dog", "Dobermann", "Miniature Pinscher", "Greater Swiss Mountain Dog", "Bernese Mountain Dog", "Appenzeller Sennenhund", "Entlebucher Sennenhund", "Boxer", "Bullmastiff", "Tibetan Mastiff", "French Bulldog", "Great Dane", "St. Bernard", "husky", "Alaskan Malamute", "Siberian Husky", "Dalmatian", "Affenpinscher", "Basenji", "pug", "Leonberger", "Newfoundland dog", "Great Pyrenees dog", "Samoyed", "Pomeranian", "Chow Chow", "Keeshond", "brussels griffon", "Pembroke Welsh Corgi", "Cardigan Welsh Corgi", "Toy Poodle", "Miniature Poodle", "Standard Poodle", "Mexican hairless dog (xoloitzcuintli)", "grey wolf", "Alaskan tundra wolf", "red wolf or maned wolf", "coyote", "dingo", "dhole", "African wild dog", "hyena", "red fox", "kit fox", "Arctic fox", "grey fox", "tabby cat", "tiger cat", "Persian cat", "Siamese cat", "Egyptian Mau", "cougar", "lynx", "leopard", "snow leopard", "jaguar", "lion", "tiger", "cheetah", "brown bear", "American black bear", "polar bear", "sloth bear", "mongoose", "meerkat", "tiger beetle", "ladybug", "ground beetle", "longhorn beetle", "leaf beetle", "dung beetle", "rhinoceros beetle", "weevil", "fly", "bee", "ant", "grasshopper", "cricket insect", "stick insect", "cockroach", "praying mantis", "cicada", "leafhopper", "lacewing", "dragonfly", "damselfly", "red admiral butterfly", "ringlet butterfly", "monarch butterfly", "small white butterfly", "sulphur butterfly", "gossamer-winged butterfly", "starfish", "sea urchin", "sea cucumber", "cottontail rabbit", "hare", "Angora rabbit", "hamster", "porcupine", "fox squirrel", "marmot", "beaver", "guinea pig", "common sorrel horse", "zebra", "pig", "wild boar", "warthog", "hippopotamus", "ox", "water buffalo", "bison", "ram (adult male sheep)", "bighorn sheep", "Alpine ibex", "hartebeest", "impala (antelope)", "gazelle", "arabian camel", "llama", "weasel", "mink", "European polecat", "black-footed ferret", "otter", "skunk", "badger", "armadillo", "three-toed sloth", "orangutan", "gorilla", "chimpanzee", "gibbon", "siamang", "guenon", "patas monkey", "baboon", "macaque", "langur", "black-and-white colobus", "proboscis monkey", "marmoset", "white-headed capuchin", "howler monkey", "titi monkey", "Geoffroy's spider monkey", "common squirrel monkey", "ring-tailed lemur", "indri", "Asian elephant", "African bush elephant", "red panda", "giant panda", "snoek fish", "eel", "silver salmon", "rock beauty fish", "clownfish", "sturgeon", "gar fish", "lionfish", "pufferfish", "abacus", "abaya", "academic gown", "accordion", "acoustic guitar", "aircraft carrier", "airliner", "airship", "altar", "ambulance", "amphibious vehicle", "analog clock", "apiary", "apron", "trash can", "assault rifle", "backpack", "bakery", "balance beam", "balloon", "ballpoint pen", "Band-Aid", "banjo", "baluster / handrail", "barbell", "barber chair", "barbershop", "barn", "barometer", "barrel", "wheelbarrow", "baseball", "basketball", "bassinet", "bassoon", "swimming cap", "bath towel", "bathtub", "station wagon", "lighthouse", "beaker", "military hat (bearskin or shako)", "beer bottle", "beer glass", "bell tower", "baby bib", "tandem bicycle", "bikini", "ring binder", "binoculars", "birdhouse", "boathouse", "bobsleigh", "bolo tie", "poke bonnet", "bookcase", "bookstore", "bottle cap", "hunting bow", "bow tie", "brass memorial plaque", "bra", "breakwater", "breastplate", "broom", "bucket", "buckle", "bulletproof vest", "high-speed train", "butcher shop", "taxicab", "cauldron", "candle", "cannon", "canoe", "can opener", "cardigan", "car mirror", "carousel", "tool kit", "cardboard box / carton", "car wheel", "automated teller machine", "cassette", "cassette player", "castle", "catamaran", "CD player", "cello", "mobile phone", "chain", "chain-link fence", "chain mail", "chainsaw", "storage chest", "chiffonier", "bell or wind chime", "china cabinet", "Christmas stocking", "church", "movie theater", "cleaver", "cliff dwelling", "cloak", "clogs", "cocktail shaker", "coffee mug", "coffeemaker", "spiral or coil", "combination lock", "computer keyboard", "candy store", "container ship", "convertible", "corkscrew", "cornet", "cowboy boot", "cowboy hat", "cradle", "construction crane", "crash helmet", "crate", "infant bed", "Crock Pot", "croquet ball", "crutch", "cuirass", "dam", "desk", "desktop computer", "rotary dial telephone", "diaper", "digital clock", "digital watch", "dining table", "dishcloth", "dishwasher", "disc brake", "dock", "dog sled", "dome", "doormat", "drilling rig", "drum", "drumstick", "dumbbell", "Dutch oven", "electric fan", "electric guitar", "electric locomotive", "entertainment center", "envelope", "espresso machine", "face powder", "feather boa", "filing cabinet", "fireboat", "fire truck", "fire screen", "flagpole", "flute", "folding chair", "football helmet", "forklift", "fountain", "fountain pen", "four-poster bed", "freight car", "French horn", "frying pan", "fur coat", "garbage truck", "gas mask or respirator", "gas pump", "goblet", "go-kart", "golf ball", "golf cart", "gondola", "gong", "gown", "grand piano", "greenhouse", "radiator grille", "grocery store", "guillotine", "hair clip", "hair spray", "half-track", "hammer", "hamper", "hair dryer", "hand-held computer", "handkerchief", "hard disk drive", "harmonica", "harp", "combine harvester", "hatchet", "holster", "home theater", "honeycomb", "hook", "hoop skirt", "gymnastic horizontal bar", "horse-drawn vehicle", "hourglass", "iPod", "clothes iron", "carved pumpkin", "jeans", "jeep", "T-shirt", "jigsaw puzzle", "rickshaw", "joystick", "kimono", "knee pad", "knot", "lab coat", "ladle", "lampshade", "laptop computer", "lawn mower", "lens cap", "letter opener", "library", "lifeboat", "lighter", "limousine", "ocean liner", "lipstick", "slip-on shoe", "lotion", "music speaker", "loupe magnifying glass", "sawmill", "magnetic compass", "messenger bag", "mailbox", "tights", "one-piece bathing suit", "manhole cover", "maraca", "marimba", "mask", "matchstick", "maypole", "maze", "measuring cup", "medicine cabinet", "megalith", "microphone", "microwave oven", "military uniform", "milk can", "minibus", "miniskirt", "minivan", "missile", "mitten", "mixing bowl", "mobile home", "ford model t", "modem", "monastery", "monitor", "moped", "mortar and pestle", "graduation cap", "mosque", "mosquito net", "vespa", "mountain bike", "tent", "computer mouse", "mousetrap", "moving van", "muzzle", "metal nail", "neck brace", "necklace", "baby pacifier", "notebook computer", "obelisk", "oboe", "ocarina", "odometer", "oil filter", "pipe organ", "oscilloscope", "overskirt", "bullock cart", "oxygen mask", "product packet / packaging", "paddle", "paddle wheel", "padlock", "paintbrush", "pajamas", "palace", "pan flute", "paper towel", "parachute", "parallel bars", "park bench", "parking meter", "railroad car", "patio", "payphone", "pedestal", "pencil case", "pencil sharpener", "perfume", "Petri dish", "photocopier", "plectrum", "Pickelhaube", "picket fence", "pickup truck", "pier", "piggy bank", "pill bottle", "pillow", "ping-pong ball", "pinwheel", "pirate ship", "drink pitcher", "block plane", "planetarium", "plastic bag", "plate rack", "farm plow", "plunger", "Polaroid camera", "pole", "police van", "poncho", "pool table", "soda bottle", "plant pot", "potter's wheel", "power drill", "prayer rug", "printer", "prison", "missile", "projector", "hockey puck", "punching bag", "purse", "quill", "quilt", "race car", "racket", "radiator", "radio", "radio telescope", "rain barrel", "recreational vehicle", "fishing casting reel", "reflex camera", "refrigerator", "remote control", "restaurant", "revolver", "rifle", "rocking chair", "rotisserie", "eraser", "rugby ball", "ruler measuring stick", "sneaker", "safe", "safety pin", "salt shaker", "sandal", "sarong", "saxophone", "scabbard", "weighing scale", "school bus", "schooner", "scoreboard", "CRT monitor", "screw", "screwdriver", "seat belt", "sewing machine", "shield", "shoe store", "shoji screen / room divider", "shopping basket", "shopping cart", "shovel", "shower cap", "shower curtain", "ski", "balaclava ski mask", "sleeping bag", "slide rule", "sliding door", "slot machine", "snorkel", "snowmobile", "snowplow", "soap dispenser", "soccer ball", "sock", "solar thermal collector", "sombrero", "soup bowl", "keyboard space bar", "space heater", "space shuttle", "spatula", "motorboat", "spider web", "spindle", "sports car", "spotlight", "stage", "steam locomotive", "through arch bridge", "steel drum", "stethoscope", "scarf", "stone wall", "stopwatch", "stove", "strainer", "tram", "stretcher", "couch", "stupa", "submarine", "suit", "sundial", "sunglasses", "sunglasses", "sunscreen", "suspension bridge", "mop", "sweatshirt", "swim trunks / shorts", "swing", "electrical switch", "syringe", "table lamp", "tank", "tape player", "teapot", "teddy bear", "television", "tennis ball", "thatched roof", "front curtain", "thimble", "threshing machine", "throne", "tile roof", "toaster", "tobacco shop", "toilet seat", "torch", "totem pole", "tow truck", "toy store", "tractor", "semi-trailer truck", "tray", "trench coat", "tricycle", "trimaran", "tripod", "triumphal arch", "trolleybus", "trombone", "hot tub", "turnstile", "typewriter keyboard", "umbrella", "unicycle", "upright piano", "vacuum cleaner", "vase", "vaulted or arched ceiling", "velvet fabric", "vending machine", "vestment", "viaduct", "violin", "volleyball", "waffle iron", "wall clock", "wallet", "wardrobe", "military aircraft", "sink", "washing machine", "water bottle", "water jug", "water tower", "whiskey jug", "whistle", "hair wig", "window screen", "window shade", "Windsor tie", "wine bottle", "airplane wing", "wok", "wooden spoon", "wool", "split-rail fence", "shipwreck", "sailboat", "yurt", "website", "comic book", "crossword", "traffic or street sign", "traffic light", "dust jacket", "menu", "plate", "guacamole", "consomme", "hot pot", "trifle", "ice cream", "popsicle", "baguette", "bagel", "pretzel", "cheeseburger", "hot dog", "mashed potatoes", "cabbage", "broccoli", "cauliflower", "zucchini", "spaghetti squash", "acorn squash", "butternut squash", "cucumber", "artichoke", "bell pepper", "cardoon", "mushroom", "Granny Smith apple", "strawberry", "orange", "lemon", "fig", "pineapple", "banana", "jackfruit", "cherimoya (custard apple)", "pomegranate", "hay", "carbonara", "chocolate syrup", "dough", "meatloaf", "pizza", "pot pie", "burrito", "red wine", "espresso", "tea cup", "eggnog", "mountain", "bubble", "cliff", "coral reef", "geyser", "lakeshore", "promontory", "sandbar", "beach", "valley", "volcano", "baseball player", "bridegroom", "scuba diver", "rapeseed", "daisy", "yellow lady's slipper", "corn", "acorn", "rose hip", "horse chestnut seed", "coral fungus", "agaric", "gyromitra", "stinkhorn mushroom", "earth star fungus", "hen of the woods mushroom", "bolete", "corn cob", "toilet paper"]


class_names = {"human": 0,
           "sneakers": 1,
           "chair": 2,
           "hat": 3,
           "lamp": 4,
           "bottle": 5,
           "cabinet/shelf": 6,
           "cup": 7,
           "car": 8,
           "glasses": 9,
           "picture/frame": 10,
           "desk": 11,
           "handbag": 12,
           "street lights": 13,
           "book": 14,
           "plate": 15,
           "helmet": 16,
           "leather shoes": 17,
           "pillow": 18,
           "glove": 19,
           "potted plant": 20,
           "bracelet": 21,
           "flower": 22,
           "monitor": 23,
           "storage box": 24,
           "plants pot/vase": 25,
           "bench": 26,
           "wine glass": 27,
           "boots": 28,
           "dining table": 29,
           "umbrella": 30,
           "boat": 31,
           "flag": 32,
           "speaker": 33,
           "trash bin/can": 34,
           "stool": 35,
           "backpack": 36,
           "sofa": 37,
           "belt": 38,
           "carpet": 39,
           "basket": 40,
           "towel/napkin": 41,
           "slippers": 42,
           "bowl": 43,
           "barrel/bucket": 44,
           "coffee table": 45,
           "suv": 46,
           "toy": 47,
           "tie": 48,
           "bed": 49,
           "traffic light": 50,
           "pen/pencil": 51,
           "microphone": 52,
           "sandals": 53,
           "canned": 54,
           "necklace": 55,
           "mirror": 56,
           "faucet": 57,
           "bicycle": 58,
           "bread": 59,
           "high heels": 60,
           "ring": 61,
           "van": 62,
           "watch": 63,
           "combine with bowl": 64,
           "sink": 65,
           "horse": 66,
           "fish": 67,
           "apple": 68,
           "traffic sign": 69,
           "camera": 70,
           "candle": 71,
           "stuffed animal": 72,
           "cake": 73,
           "motorbike/motorcycle": 74,
           "wild bird": 75,
           "laptop": 76,
           "knife": 77,
           "cellphone": 78,
           "paddle": 79,
           "truck": 80,
           "cow": 81,
           "power outlet": 82,
           "clock": 83,
           "drum": 84,
           "fork": 85,
           "bus": 86,
           "hanger": 87,
           "nightstand": 88,
           "pot/pan": 89,
           "sheep": 90,
           "guitar": 91,
           "traffic cone": 92,
           "tea pot": 93,
           "keyboard": 94,
           "tripod": 95,
           "hockey stick": 96,
           "fan": 97,
           "dog": 98,
           "spoon": 99,
           "blackboard/whiteboard": 100,
           "balloon": 101,
           "air conditioner": 102,
           "cymbal": 103,
           "mouse": 104,
           "telephone": 105,
           "pickup truck": 106,
           "orange": 107,
           "banana": 108,
           "airplane": 109,
           "luggage": 110,
           "skis": 111,
           "soccer": 112,
           "trolley": 113,
           "oven": 114,
           "remote": 115,
           "combine with glove": 116,
           "paper towel": 117,
           "refrigerator": 118,
           "train": 119,
           "tomato": 120,
           "machinery vehicle": 121,
           "tent": 122,
           "shampoo/shower gel": 123,
           "head phone": 124,
           "lantern": 125,
           "donut": 126,
           "cleaning products": 127,
           "sailboat": 128,
           "tangerine": 129,
           "pizza": 130,
           "kite": 131,
           "computer box": 132,
           "elephant": 133,
           "toiletries": 134,
           "gas stove": 135,
           "broccoli": 136,
           "toilet": 137,
           "stroller": 138,
           "shovel": 139,
           "baseball bat": 140,
           "microwave": 141,
           "skateboard": 142,
           "surfboard": 143,
           "surveillance camera": 144,
           "gun": 145,
           "Life saver": 146,
           "cat": 147,
           "lemon": 148,
           "liquid soap": 149,
           "zebra": 150,
           "duck": 151,
           "sports car": 152,
           "giraffe": 153,
           "pumpkin": 154,
           "Accordion/keyboard/piano": 155,
           "radiator": 156,
           "converter": 157,
           "tissue": 158,
           "carrot": 159,
           "washing machine": 160,
           "vent": 161,
           "cookies": 162,
           "cutting/chopping board": 163,
           "tennis racket": 164,
           "candy": 165,
           "skating and skiing shoes": 166,
           "scissors": 167,
           "folder": 168,
           "baseball": 169,
           "strawberry": 170,
           "bow tie": 171,
           "pigeon": 172,
           "pepper": 173,
           "coffee machine": 174,
           "bathtub": 175,
           "snowboard": 176,
           "suitcase": 177,
           "grapes": 178,
           "ladder": 179,
           "pear": 180,
           "american football": 181,
           "basketball": 182,
           "potato": 183,
           "paint brush": 184,
           "printer": 185,
           "billiards": 186,
           "fire hydrant": 187,
           "goose": 188,
           "projector": 189,
           "sausage": 190,
           "fire extinguisher": 191,
           "extension cord": 192,
           "facial mask": 193,
           "tennis ball": 194,
           "chopsticks": 195,
           "Electronic stove and gas st": 196,
           "pie": 197,
           "frisbee": 198,
           "kettle": 199,
           "hamburger": 200,
           "golf club": 201,
           "cucumber": 202,
           "clutch": 203,
           "blender": 204,
           "tong": 205,
           "slide": 206,
           "hot dog": 207,
           "toothbrush": 208,
           "facial cleanser": 209,
           "mango": 210,
           "deer": 211,
           "egg": 212,
           "violin": 213,
           "marker": 214,
           "ship": 215,
           "chicken": 216,
           "onion": 217,
           "ice cream": 218,
           "tape": 219,
           "wheelchair": 220,
           "plum": 221,
           "bar soap": 222,
           "scale": 223,
           "watermelon": 224,
           "cabbage": 225,
           "router/modem": 226,
           "golf ball": 227,
           "pine apple": 228,
           "crane": 229,
           "fire truck": 230,
           "peach": 231,
           "cello": 232,
           "notepaper": 233,
           "tricycle": 234,
           "toaster": 235,
           "helicopter": 236,
           "green beans": 237,
           "brush": 238,
           "carriage": 239,
           "cigar": 240,
           "earphone": 241,
           "penguin": 242,
           "hurdle": 243,
           "swing": 244,
           "radio": 245,
           "CD": 246,
           "parking meter": 247,
           "swan": 248,
           "garlic": 249,
           "french fries": 250,
           "horn": 251,
           "avocado": 252,
           "saxophone": 253,
           "trumpet": 254,
           "sandwich": 255,
           "cue": 256,
           "kiwi fruit": 257,
           "bear": 258,
           "fishing rod": 259,
           "cherry": 260,
           "tablet": 261,
           "green vegetables": 262,
           "nuts": 263,
           "corn": 264,
           "key": 265,
           "screwdriver": 266,
           "globe": 267,
           "broom": 268,
           "pliers": 269,
           "hammer": 270,
           "volleyball": 271,
           "eggplant": 272,
           "trophy": 273,
           "board eraser": 274,
           "dates": 275,
           "rice": 276,
           "tape measure/ruler": 277,
           "dumbbell": 278,
           "hamimelon": 279,
           "stapler": 280,
           "camel": 281,
           "lettuce": 282,
           "goldfish": 283,
           "meat balls": 284,
           "medal": 285,
           "toothpaste": 286,
           "antelope": 287,
           "shrimp": 288,
           "rickshaw": 289,
           "trombone": 290,
           "pomegranate": 291,
           "coconut": 292,
           "jellyfish": 293,
           "mushroom": 294,
           "calculator": 295,
           "treadmill": 296,
           "butterfly": 297,
           "egg tart": 298,
           "cheese": 299,
           "pomelo": 300,
           "pig": 301,
           "race car": 302,
           "rice cooker": 303,
           "tuba": 304,
           "crosswalk sign": 305,
           "papaya": 306,
           "hair dryer": 307,
           "green onion": 308,
           "chips": 309,
           "dolphin": 310,
           "sushi": 311,
           "urinal": 312,
           "donkey": 313,
           "electric drill": 314,
           "spring rolls": 315,
           "tortoise/turtle": 316,
           "parrot": 317,
           "flute": 318,
           "measuring cup": 319,
           "shark": 320,
           "steak": 321,
           "poker card": 322,
           "binoculars": 323,
           "llama": 324,
           "radish": 325,
           "noodles": 326,
           "mop": 327,
           "yak": 328,
           "crab": 329,
           "microscope": 330,
           "barbell": 331,
           "Bread/bun": 332,
           "baozi": 333,
           "lion": 334,
           "red cabbage": 335,
           "polar bear": 336,
           "lighter": 337,
           "mangosteen": 338,
           "seal": 339,
           "comb": 340,
           "eraser": 341,
           "pitaya": 342,
           "scallop": 343,
           "pencil case": 344,
           "saw": 345,
           "table tennis  paddle": 346,
           "okra": 347,
           "starfish": 348,
           "monkey": 349,
           "eagle": 350,
           "durian": 351,
           "rabbit": 352,
           "game board": 353,
           "french horn": 354,
           "ambulance": 355,
           "asparagus": 356,
           "hoverboard": 357,
           "pasta": 358,
           "target": 359,
           "hotair balloon": 360,
           "chainsaw": 361,
           "lobster": 362,
           "iron": 363,
           "flashlight": 364,}
seen_classes = {"toilet": 0,
              "bed": 1,
              "chair": 2,
              "sofa": 3,
              "dresser": 4,
              "table": 5,
              "cabinet": 6,
              "bookshelf": 7,
              "pillow": 8,
              "sink": 9,
              "bathtub": 10,
              "refridgerator": 11,
              "desk": 12,
              "night stand": 13,
              "counter": 14,
              "door": 15,
              "curtain": 16,
              "box": 17,
              "lamp": 18,
              "bag": 19,}

o365_classes = list(class_names.keys())
novel_classes = list(seen_classes.keys())

# A subset of these class names are modified from the default ImageNet class names sourced from Anish Athalye's imagenet-simple-labels.
# 
# These edits were made via trial and error and concentrated on the lowest performing classes according to top_1 and top_5 accuracy on the ImageNet training set for the RN50, RN101, and RN50x4 models. These tweaks improve top_1 by 1.5% on ViT-B/32 over using the default class names. Alec got bored somewhere along the way as gains started to diminish and never finished updating / tweaking the list. He also didn't revisit this with the better performing RN50x16, RN50x64, or any of the ViT models. He thinks it's likely another 0.5% to 1% top_1 could be gained from further work here. It'd be interesting to more rigorously study / understand this.
# 
# Some examples beyond the crane/crane -> construction crane / bird crane issue mentioned in Section 3.1.4 of the paper include:
# 
# - CLIP interprets "nail" as "fingernail" so we changed the label to "metal nail".
# - ImageNet kite class refers to the bird of prey, not the flying toy, so we changed "kite" to "kite (bird of prey)"
# - The ImageNet class for red wolf seems to include a lot of mislabeled maned wolfs so we changed "red wolf" to "red wolf or maned wolf"
imagenet_templates = [
    'a bad photo of a {}.',
    'a photo of many {}.',
    'a sculpture of a {}.',
    'a photo of the hard to see {}.',
    'a low resolution photo of the {}.',
    'a rendering of a {}.',
    'graffiti of a {}.',
    'a bad photo of the {}.',
    'a cropped photo of the {}.',
    'a tattoo of a {}.',
    'the embroidered {}.',
    'a photo of a hard to see {}.',
    'a bright photo of a {}.',
    'a photo of a clean {}.',
    'a photo of a dirty {}.',
    'a dark photo of the {}.',
    'a drawing of a {}.',
    'a photo of my {}.',
    'the plastic {}.',
    'a photo of the cool {}.',
    'a close-up photo of a {}.',
    'a black and white photo of the {}.',
    'a painting of the {}.',
    'a painting of a {}.',
    'a pixelated photo of the {}.',
    'a sculpture of the {}.',
    'a bright photo of the {}.',
    'a cropped photo of a {}.',
    'a plastic {}.',
    'a photo of the dirty {}.',
    'a jpeg corrupted photo of a {}.',
    'a blurry photo of the {}.',
    'a photo of the {}.',
    'a good photo of the {}.',
    'a rendering of the {}.',
    'a {} in a video game.',
    'a photo of one {}.',
    'a doodle of a {}.',
    'a close-up photo of the {}.',
    'a photo of a {}.',
    'the origami {}.',
    'the {} in a video game.',
    'a sketch of a {}.',
    'a doodle of the {}.',
    'a origami {}.',
    'a low resolution photo of a {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'a photo of the clean {}.',
    'a photo of a large {}.',
    'a rendition of a {}.',
    'a photo of a nice {}.',
    'a photo of a weird {}.',
    'a blurry photo of a {}.',
    'a cartoon {}.',
    'art of a {}.',
    'a sketch of the {}.',
    'a embroidered {}.',
    'a pixelated photo of a {}.',
    'itap of the {}.',
    'a jpeg corrupted photo of the {}.',
    'a good photo of a {}.',
    'a plushie {}.',
    'a photo of the nice {}.',
    'a photo of the small {}.',
    'a photo of the weird {}.',
    'the cartoon {}.',
    'art of the {}.',
    'a drawing of the {}.',
    'a photo of the large {}.',
    'a black and white photo of a {}.',
    'the plushie {}.',
    'a dark photo of a {}.',
    'itap of a {}.',
    'graffiti of the {}.',
    'a toy {}.',
    'itap of my {}.',
    'a photo of a cool {}.',
    'a photo of a small {}.',
    'a tattoo of the {}.',
]

print(f"{len(class_names)} classes, {len(imagenet_templates)} templates")


# A similar, intuition-guided trial and error based on the ImageNet training set was used for templates. This list is pretty haphazard and was gradually made / expanded over the course of about a year of the project and was revisited / tweaked every few months. A surprising / weird thing was adding templates intended to help ImageNet-R performance (specifying different possible renditions of an object) improved standard ImageNet accuracy too.
# 
# After the 80 templates were "locked" for the paper, we ran sequential forward selection over the list of 80 templates. The search terminated after ensembling 7 templates and selected them in the order below.
# 
# 1. itap of a {}.
# 2. a bad photo of the {}.
# 3. a origami {}.
# 4. a photo of the large {}.
# 5. a {} in a video game.
# 6. art of the {}.
# 7. a photo of the small {}.
# 
# Speculating, we think it's interesting to see different scales (large and small), a difficult view (a bad photo), and "abstract" versions (origami, video game, art), were all selected for, but we haven't studied this in any detail. This subset performs a bit better than the full 80 ensemble reported in the paper, especially for the smaller models.

# # Loading the Images
# 
# The ILSVRC2012 datasets are no longer available for download publicly. We instead download the ImageNet-V2 dataset by [Recht et al.](https://arxiv.org/abs/1902.10811).
# 
# If you have the ImageNet dataset downloaded, you can replace the dataset with the official torchvision loader, e.g.:
# 
# ```python
# images = torchvision.datasets.ImageNet("path/to/imagenet", split='val', transform=preprocess)
# ```

# images = ImageNetV2Dataset(transform=preprocess)
# loader = torch.utils.data.DataLoader(images, batch_size=32, num_workers=2)


# # Creating zero-shot classifier weights

def zeroshot_classifier(classnames, templates):
    with torch.no_grad():
        zeroshot_weights = []
        for classname in tqdm(classnames):
            texts = [template.format(classname) for template in templates] #format with class
            texts = clip.tokenize(texts).cuda() #tokenize
            class_embeddings = model.encode_text(texts) #embed with text encoder
            class_embeddings /= class_embeddings.norm(dim=-1, keepdim=True)
            class_embedding = class_embeddings.mean(dim=0)
            class_embedding /= class_embedding.norm()
            zeroshot_weights.append(class_embedding)
        zeroshot_weights = torch.stack(zeroshot_weights, dim=1).cuda()
        zeroshot_weights = torch.transpose(zeroshot_weights, 0, 1)
    return zeroshot_weights


save_path = 'scannet_clip_a+cname_rn50_manyprompt_365c_coda.npy'
save_novel_path = 'scannet_clip_a+cname_rn50_manyprompt_20c_coda.npy'
zeroshot_weights = zeroshot_classifier(o365_classes, imagenet_templates)
novel_zeroshot_weights = zeroshot_classifier(novel_classes, imagenet_templates)
breakpoint()
np.save(save_path, zeroshot_weights.cpu().numpy())
np.save(save_novel_path, novel_zeroshot_weights.cpu().numpy())
